# railway.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/src/builder-io-react-test/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node dist/server/node-build.mjs"